[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --no-input"]

[start]
cmd = "python manage.py migrate --no-input && gunicorn ecommerce.wsgi --bind 0.0.0.0:$PORT --log-file -"